### ISSUE TITLE
Ethernet | No devices found

### ISSUE THREAD

**Issue by DanaMC18** [Tapanila/SharpCaster#100]
I made a simplified version of the [Console](https://github.com/Tapanila/SharpCaster/tree/master/SharpCaster.Console) app, but I am not finding any devices. In the console I get `"Started locating chromecasts!"`, but then the application just hangs. I get neither `"No Chromecasts found"` nor `"Device found..."`. I suspect the issue may be with `await ChromecastService.StartLocatingDevices()`.

Could this possibly be due to the fact that I am currently connecting to my Chromecast via an ethernet connection? (FWIW, at some point I'd like to search for all devices on a particular LAN or range of IPs.)

I also looked into the DeviceLocator class and saw that it uses Rssdp. Doing more research on Chromecasts I saw that they no longer use SSDP but rather mDNS/DNS-SD. Is this true? Could the fact that I am using a newer Chromecast have any bearing on this?

For a bit of detail: I already created a custom Receiver and Sender application. I have Chromecasts on various TVs and via the Sender application would like to dynamically display different information on these TVs based on users' preferences. **I would ideally like to try to initialize a session with these Chromecasts without going through the Chrome extension popup.** That is my main goal and it appears as if Sharpcaster allows this to happen so I thought I'd test it out. If I am mistaken, please let me know.

And in case it helps, my console code is as follows
```
        static readonly ChromecastService ChromecastService = ChromecastService.Current;
        static SharpCasterDemoController _controller;

        static void Main(string[] args)
        {
            DoStuff().Wait();
            var input = Console.ReadLine();
        }

        private static async Task DoStuff()
        {
            ChromecastService.ChromeCastClient.ConnectedChanged += ChromeCastClient_Connected;

            System.Console.WriteLine("Started locating chromecasts!");
            var devices = await ChromecastService.StartLocatingDevices();  // i believe the code is just hanging here

            if (devices.Count == 0)
            {
                System.Console.WriteLine("No chromecasts found");
                return;
            }

            var firstChromecast = devices.First();
            System.Console.WriteLine("Device found " + firstChromecast.FriendlyName);
            ChromecastService.ConnectToChromecast(firstChromecast);
        }

        private static async void ChromeCastClient_Connected(object sender, EventArgs e)
        {
            System.Console.WriteLine("Connected to chromecast");
            if (_controller == null)
            {
                _controller = await ChromecastService.ChromeCastClient.LaunchSharpCaster();
            }
        }

**Comment by Tapanila** [comment]
Hey,

The finding of chromecasts does normally work totally fine but in some cases like multiple networks (ethernet, WLAN, VMWare, Hyper-v, VirtualBox) you need to modify the code a bit to tell the library which IP address it should bind itself into. 

```
//You can use this, Where 192.168.1.2 is your machines local ip
ObservableCollection<Chromecast> chromecasts = await ChromecastService.Current.StartLocatingDevices("192.168.1.2);
```

**Comment by DanaMC18** [comment]
Thank you for the prompt response.

With that modification I am at least getting the "No chromecasts found" message.  That may come down to a network issue on my end.

**Comment by Tapanila** [comment]
If you need further help please open the issue again
