### ISSUE TITLE
Update RSSDP package

### ISSUE THREAD

**Issue by bbougot** [Tapanila/SharpCaster#101]
Would be great to update RSSDP package to current version (discovering fixes, better error handling, ...)

**Comment by wind-rider** [comment]
I believe that's done as a part of my PR around protobuf

**Comment by bbougot** [comment]
@Tapanila Any ETA for a merge of this PR?

**Comment by wind-rider** [comment]
Sorry, I made a mistake, i checked and it is not part of that PR. I do remember that I noticed the possibility of updating rssdp too.

**Comment by Tapanila** [comment]
I will try to merge all of the stuff in today (RSSDP update, Change of Protobuf library and merge dev to master). If I face any issues with the stuff then I might not do the merge to master but I will publish a dev release of nuget package

**Comment by Tapanila** [comment]
Released 0.4.0
