### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Tapanila** [Tapanila/SharpCaster#104]
Would be awesome to have a logo for the project

**Comment by fahadabdulaziz** [comment]
Hi,

First I want to thank for this great lib.

What do you think of this: http://prntscr.com/fioxfr

**Comment by Tapanila** [comment]
I think the Sharp is too large on it compared to signals.

Just did some searching on a web and I think something like this https://i1.wp.com/storage.googleapis.com/cdn.vlogg.com/uploads/2013/12/GoogleChromecastCastIcon.jpg?ssl=1 with Sharp inside of the TV would fit nicely.

**Comment by fahadabdulaziz** [comment]
Yes I think the sharp is the casting one :-)

What do you think about this one: http://prntscr.com/fj1eke

**Comment by Tapanila** [comment]
I think that would fit perfectly.

Could you provide the following versions of it:
- 64x64 png with transparent background (this goes for nuget.org)
- Largest you can or SVG if possible.

**Comment by fahadabdulaziz** [comment]
Great, Here they are :-)

![sharpcastlogolarge](https://user-images.githubusercontent.com/5483584/27091394-acd6ecd4-5068-11e7-8e51-e29e6b4d0778.png)
![sharpcastlogosmall](https://user-images.githubusercontent.com/5483584/27091393-acc82dd4-5068-11e7-8182-87f93f397f6e.png)

**Comment by Tapanila** [comment]
Thanks for the logo. Added it to repository and will push new packages with the logo with next version
