### ISSUE TITLE
Issues while trying to detect and connect to a ChromeCast

### ISSUE THREAD

**Issue by bbougot** [Tapanila/SharpCaster#105]
I use SharpCaster to cast the media to a Chromecast, but most of the time, the Chromecast could not be found. Worse, when the Chromecast is found, SharpCaster could not connect to the device (Timeout or Socket exceptions are thrown).

**Comment by Tapanila** [comment]
Are you using Sharpcaster on a desktop? Do you know if those computers have multiple network cards? If you have installed VMWare Workstation, VirtualBox or Hyper-v this happens automatically and it has problems to find the device.

I haven't seen any problems on connecting to the device if it has been found. Would be really interested in these scenarios. Especially if you have any clues how to reproduce the problem.

**Comment by Tapanila** [comment]
Need more information to be able to do anything about this issue
