### ISSUE TITLE
Chromecast discovery problems

### ISSUE THREAD

**Issue by Tapanila** [Tapanila/SharpCaster#106]
Currently the library has some issues on discovering chromecasts on some computers.

I was thinking of switching from RSSDP to https://github.com/tmds/Tmds.MDns library which should better support discovery of chromecast devices.

**Comment by kakone** [comment]
SSDP was used in GoogleCast v1 SDK.
mDNS is the primary way of discovering a Chromecast that supports the v2+ API.
Personnaly, I used [Zeroconf](https://github.com/onovotny/Zeroconf) to [discover the devices](https://github.com/kakone/GoogleCast/blob/master/GoogleCast/DeviceLocator.cs).

**Comment by Tapanila** [comment]
I was looking into Zeroconf but not really happy with the reactive dependency.
I want to decrease the number of dependencies on SharpCaster so that's why I was looking into Tmds.MDns.

On the other hand have you tested the zeroconf implementation on multiple devices successfully? Especially interested on computers with multiple virtual network cards and multiple private ips.

**Comment by Tapanila** [comment]
I will switch to Tmds.MDns library in a near future as it seem really reliable on desktop and mobile usage.

**Comment by Tapanila** [comment]
Fixed #119
