### ISSUE TITLE
Casting a custom application view

### ISSUE THREAD

**Issue by replaysMike** [Tapanila/SharpCaster#107]
I've been reviewing the api a little while, and I'm wondering what types of solutions you've thought about in terms of casting a custom screen or graphics buffer. We would like to cast a custom display output (Direct3D / Windows Forms / GDI). The only way I can currently think of doing this is to feed the window display into a video encoder & stream it to the device using Directshow or something to the media channel. I would imagine the chrome tab casting isn't doing this but something a little more efficient.

Any thoughts on how to do this with the cast api?

**Comment by Tapanila** [comment]
I'm not sure how Chrome is archiving their screen sharing functionality but the only way I know you could archive it yourself is the way you described.

There is one other option that I have thought. You create custom chromecast receiver application and then you can start showing that, this requires you to do HTML5 UI for it to work really well.

**Comment by replaysMike** [comment]
It seems like the Remote Display / Unity Remote Display would be the way to
go. I'm digging through the API to assess how difficult this will be under
Windows.

**Comment by Tapanila** [comment]
Did you get any further with Remote Display / Unity Remote Display APIs?

**Comment by xmedeko** [comment]
If any HTML5 app can be used for UI, then any HTML5 remote screen sharing, like [noVNC](https://kanaka.github.io/noVNC/) (but other are available.)
