### ISSUE TITLE
White screen when casting (CC V2)

### ISSUE THREAD

**Issue by Jelle-Verdoodt** [Tapanila/SharpCaster#108]
When I try to cast to the Chromecast v2, it just displays a white page.  If I recall correctly, the controller text has something like: "Ready to cast" instead of the URL I want to cast.
When the white page is shown and I cast again then the chromecast correctly displays the webpage.

This issue does not happen while casting to V1.  A quick fix for this is connect back to the chromecast and casting the webpage again.

Any thoughts?

**Comment by Tapanila** [comment]
Does this behavior happen every time? if so can you provide me the sample project that would cause this. Then I can probably fix it

**Comment by Jelle-Verdoodt** [comment]
It did happen everytime but it might have been my fault. 
I fixed the issue by waiting between the LaunchWeb & the LoadURL functions. Maybe the connection speed wasn't fast enough at my part?

Thanks for the great library :)
