### ISSUE TITLE
ChromeCast crashes at certain webpage in WebController

### ISSUE THREAD

**Issue by thomas479** [Tapanila/SharpCaster#109]
I am using a slightly modified version of the demo console project to let my ChromeCast display a specific webpage. This webpage is displays "widgets" from a web-application. These widgets load in a sequence, so you will see widget 1 for 30 seconds and then it changes to widget 2 for 30 seconds. This loop should run indefinitely, but it does not.

The ChromeCast crashes after 10 minutes or so, the boot screen is suddenly displayed and then I see the nice nature pictures from Google.

We use this demo console project for two months now without any issue, but since we added the second widget to the loop, the ChromeCast can't cope with that for some reason.

I personally don't think ShaprCaster is to blame, but are you aware of any limitations that could possibly cause this behaviour? When I check memory usage on my local Chrome installation this is normal (around 60MB) and this is the same when I only have one widget refreshing every 30 seconds.

**Comment by Tapanila** [comment]
Haven't seen this kind of behavior. But haven't really been using the chromecast this way. I think you could host your own custom receiver and then connect your chrome to chromecast debug session to see if the memory usage is a problem or maybe some code is causing errors?

The source of custom receiver that SharpCaster is using can be found here:
https://github.com/DeMille/url-cast-receiver

If you want help to debug the problem you can send the project to teemu@tapanila.net and I can take a look at it.

**Comment by thomas479** [comment]
Thanks Tapanila, I will research hosting my own custom receiver and having a debug session on that!

**Comment by Tapanila** [comment]
If you need any more help on this feel free to open the issue again

**Comment by thomas479** [comment]
For the record (if someone finds this issue in the future like https://xkcd.com/979/) we eventually used a Raspberry Pi with Chromium in kiosk mode. This proved to be more reliable as sometimes our WiFi hicks up and make the ChromeCasts stop.
