### ISSUE TITLE
Chromecast Discovery in UWP

### ISSUE THREAD

**Issue by wind-rider** [Tapanila/SharpCaster#113]
In your UWP app you could also consider using

```csharp
using Windows.Media.DialProtocol;

.......

    DialDevicePicker _picker = new DialDevicePicker();
    _picker.DialDeviceSelected += _picker_DialDeviceSelected; ;
    _picker.Show(CoreApplication.GetCurrentView().CoreWindow.Bounds); // you can choose where to show it, here I let it fly in from the top-left of the app window

.....
    private void _picker_DialDeviceSelected(DialDevicePicker sender, DialDeviceSelectedEventArgs args)
    {
        Debug.WriteLine(args.SelectedDialDevice.Id);
    }
```

since Chromecasts show themselves as DIAL devices. It gives a device picker + device discovery logic.

**Comment by wind-rider** [comment]
Oddly enough the DialDeviceSelected event doesn't get called when I click my chromecast in that devicepicker window :/

**Comment by Tapanila** [comment]
I will take a look on this if I can get the IP of the device.

Not really that interested into this feature since it would be extra effort and only for one platform.

**Comment by wind-rider** [comment]
I'm currently trying to remake that Picker UI in a Flyout control, but I'm still having some issues fixing the UWP sample app.

**Comment by Tapanila** [comment]
Not going to implement this
