### ISSUE TITLE
Feedback from kakone

### ISSUE THREAD

**Issue by wind-rider** [Tapanila/SharpCaster#117]
@Tapanila I [asked](https://github.com/kakone/GoogleCast/issues/1) @kakone on his thoughts about SharpCaster and his motivation to start a new library.

He gave some feedback with points that I see value in - what do you think of them?

The .Net standard thing is something that'll have to wait until UWP will be supported, but what do you think of things like `events` vs `async-await`?

**Comment by Tapanila** [comment]
I'm not super happy with the current look and feel of SharpCaster.

It works but the code is too complicated and it's hard to extend/modify.

I would much prefer async-await pattern over the events pattern. Currently it is little bit of mix and that is not a good thing. Haven't looked into kakone version that much just for the mdns parts.

**Comment by Tapanila** [comment]
Closing this and we can continue the discussion on #119
