### ISSUE TITLE
Refactoring tasks

### ISSUE THREAD

**Issue by Tapanila** [Tapanila/SharpCaster#118]
Here's list of tasks for refactoring:

- [ ] Instead of using events all functions (like Launch application, load media) should be refactored to be async like here: https://github.com/kakone/GoogleCast/blob/master/GoogleCast/Sender.cs
- [ ] Move samples out of this repository to SharpCaster.Samples
- [ ] Refactor test cases
- [ ] Extract application specific channels out of this project and create separate NuGet packages out of them (Youtube, Plex, Web page casting)
- [ ] Extract chromecast discovery out of this project and create a separate NuGet package out of default implementation. This enables an easier switch to different protocols for different platforms.
- [ ] Enable the control of multiple chromecasts
- [ ] Get rid of separate build solution

Work will be done in Refactoring branch

**Comment by wind-rider** [comment]
Are you sure about creating a separate nuget package for discover? To me it comes across as overkill, I would assume that one discovery approach should be enough?

**Comment by Tapanila** [comment]
You might want different discovery on different platforms (Linux, Windows, iPhone, Android) so that's why I will take it outside. Anyway, it is not a big thing to extract it from the main project.

Also, I want to learn how to split stuff into multiple NuGet packages in a smart manner so that's one of the driving factors also.

I ended starting to rewrite the whole project. It will look a lot more like that Kakone built. All of the commands will be async and respond with chromecast response. It will also have the event handlers for multiple sender scenarios. I will soon start putting it into Refactoring branch once I got all of the basics done

**Comment by wind-rider** [comment]
Sounds good! 👍

**Comment by wind-rider** [comment]
Maybe you know this alraedy, but as for building the multiple NuGet packages - you can do something like in https://github.com/google/protobuf/blob/master/csharp/build_packages.bat

There the information for the NuGet packages is stored in each csproj file and the `nuget pack` command for the solution generates the packages for the projects in that solution.

**Comment by Tapanila** [comment]
Closing this and continuing the discussions and tasks on #119
