### ISSUE TITLE
Custom interface on Chromecast device.

### ISSUE THREAD

**Issue by mopenstein** [Tapanila/SharpCaster#120]
First off let me say great work! Your work has saved me so much time, thank you.

My question is basically when I load a video on onto my device it loads a SharpCaster demo "channel" on the Chromecast. Is it possible, and if so, how do I go about creating my own custom channel on the Chromecast?

**Comment by Tapanila** [comment]
Glad to hear you like it.

You can and should use a custom receiver that can be branded for the project you are working with. SharpCaster demo is there to just make it easier to debug for me.

Here's instructions how to build [custom receiver](https://developers.google.com/cast/docs/custom_receiver)

**Comment by mopenstein** [comment]
Thanks for that.

I'm sure this is simple but where can I enter my custom receiver id in code?

**Comment by BenTomsett** [comment]
Did you ever work this out @mopenstein?

**Comment by haraldjordan78** [comment]
You can change the appid in SharpCasterDemoController.cs or WebController.cs in the SharpCaster.Portable project or better just provide your own custom Controller and channel there.
