### ISSUE TITLE
CastController.StopApplication() does not change ChromeCastClient.Connected property

### ISSUE THREAD

**Issue by marufbd** [Tapanila/SharpCaster#123]
CastController.StopApplication() call does stop the app on chromecast, but does not raise Connected_Changed event, only ChromecastStatusChanged is raised and once connected the ChromeCastClient.Connected property remains true, no matter how long the application is stopped

After StoApplication the ConnectToChromecast does nothing. So it makes it impossible to re-connect after stopapplication

**Comment by Tapanila** [comment]
The stop application should work. All my current work is on refactoring branch so I will write a test case and fix this issue there. I'm currently making progress very slowly because of my other priorities.

**Comment by marufbd** [comment]
@Tapanila I think refactoring branch does not have that problem, when are you gonna release v1.0.0
I think the refactor branch has some dependency not compatible with PCL 4.5.1. I am currently migrating to .net standard. Do you think i should be ok to use the refactor branch until you release on nuget.

**Comment by Tapanila** [comment]
Currently, the refactor branch is still WIP. Meaning it has problems like playmedia doesn't work

But I would suggest starting using it since it will be breaking major change.
