### ISSUE TITLE
A few questions about Chromecast

### ISSUE THREAD

**Issue by sensboston** [Tapanila/SharpCaster#124]
Hello! First of all, I wanna say "Thanks" for the good project. I easily added Chromecast support (as a new feature) to my UWP app ["Cast to"](https://www.microsoft.com/en-us/store/p/cast-to/9nblggh5292q).

But I'm very new to Chromecast API and have a few questions; maybe you can help me to save time for research :)

First, do you know, how to provide a media orientation to Chromecast (portrait or landscape) for pictures and videos? Looks like Chromecast don't care about EXIF data in media, and don't have any corresponding metadata. I don't want to touch pictures and videos on the W10 device (phone or desktop)...

Also, currently I'm using your controller implementation, **SharpCasterDemoController**. It works fine but I'd like to change an app name. I registered my account at Google's chromecast page, paid $5, created app and got id. So, if I do
`_controller.ApplicationId = _myAppId;`
will it work if my app in _unpublished_ state? Google don't provide a way to register UWP apps :( BTW, how did you registered "SharpCaster Demo", as a web app? Could you describe all steps please.

And third: I'm able to cast pics and videos to my Chromecast (tested from the desktop, will test on phone) but image/video loading takes a long time (not too long but much longer than casting to DLNA device). I do have my own http server, and it works pretty good for DLNA but not for Chromecast. Could you provide some tips or advises (I didn't "dig" hard for now - i.e. didn't analyze traffic).

Thanks a lot!

**Comment by Tapanila** [comment]
Nice to hear you found a good use for this library.

1. Media orientation
I think it might only support landscape pictures out of the box. If you want portrait support you would have to write custom receiver with JS to handle the portrait video.

2. Changing app name
Create a new class and copy & paste this class into it https://github.com/Tapanila/SharpCaster/blob/master/SharpCaster/Controllers/SharpCasterDemoController.cs and change the appID on bottom and name of it.

3. Registering your chromecast application
Just go here and follow instructions how to register for styled media receiver.
https://developers.google.com/cast/docs/registration

4. Loading times are long
Haven't looked into this part that much since I have always had different team handling chromecast playback on the server side. The chromecast is basically a browser, so if you can get the load times to be quick with a browser you should be able to achieve similar experience on chromecast.

**Comment by sensboston** [comment]
Thanks a lot for the great and clear answers, Teemu! I'm really appreciate that!

Could you please extend a little (great, if you have an example) #1 for me? What is the custom receiver, how to deploy it to Chromecast (by using your library)? Sorry for the stupid questions but my work with Chromecast begun from your code (I tried a few projects but your code started working out of box), not from the Google's API references :) I know, it's a bad practice but I need to use Chromecast (actually, not me but some of my customers - I'm pretty happy with DLNA renderers) as a simple media renderer.

**Comment by sensboston** [comment]
You know, I checked some Android apps and they show pics/videos much-much faster :( Probably these apps are using "Remote Display" API https://developers.google.com/cast/docs/remote ?

Do you know any UWP/C# implementation/port of this API? 

**MediaChannel.LoadMedia** is working pretty slow, I have about 5-7 seconds delays (with black screen) between pictures. mp4 videos are also playing with delays :( And I'm 100% sure it's not a bug/delay in my HTTP server code 'cause casting to DLNA is working pretty nice. Any suggestions?

**Comment by Tapanila** [comment]
I haven't seen any ports (node, java or C#) of Remote Display API.

Most of the application that has good chromecast support is because of a combination of client (phone, browser) and chromecast client combination. So writing a good chromecast receiver can make the experience way better. Like if your videos are short you should start pre-loading a new one while old one is still playing same with pictures if you want to do slideshows.

I haven't personally done any advanced chromecast receiver application development so can't really help there.

**Comment by sensboston** [comment]
My client (UWP app) is also a server, no external sites involved. I'm playing/showing local media only via HTTP server (I'm using [Peter Waher's implementation](https://github.com/PeterWaher/IoTGateway/tree/master/Networking))

Your advise for media pre-loading doesn't fit my app architecture (please take a look to the app's screenshots in my first post): I have a media page with thumbnails, user tap on pic/video, and should see it on big screen TV (it's very intuitive). Of course I have a slideshow mode, but looks like I have a different issue - videos are also playing with delays (but on DLNA very smoothly). But maybe HTTP server I'm using has some issues with Cromecast.

I'll create a simple test app for slideshow with medias on external and internal HTTP servers, and tell you a results.

**Comment by sensboston** [comment]
OK, I created a very simple UWP slideshow program, easy to build and test, you may download it [from here](https://www.dropbox.com/s/60zchugtybzxijg/CromecastTest.zip?dl=0). Could you please take a look? I added modified Peter's code; unfortunately hes code have a bug/feature, I already submitted patch but looks like he forgot to modify sources and build new NuGet package). Also, don't be afraid of archive size, it's just a content :) Source code is straight forward a pretty simple, just a few lines of code.

By the way, this test app shows the same behavior on casting to Chromecast as my real app, "Cast to" i.e. big delays between loading pictures and gaps and glitches playing mp4 video (on slide #8).

I especially created a simple HTML/JS built-in web app to test image loading performance. As expected, it works pretty good, you may try it by yourself (run UWP app, on second PC open browser and type http://192.168.1.100/slideshow to run app or just http://192.168.1.100/1.jpg or http://192.168.1.100/8.mp4 ; of course replace 192.168.1.100 by real IP address of PC where UWP app is running).

So, could you **please** teach me or show me, how to improve Chromecast performance? It usually plays external mp4's (even "heave", big ones, Full HD) very well but not from my apps :(

**Comment by sensboston** [comment]
Hi Teemu, could you add something to my post? It's a showstopper for me now, I can't release an update with so buggy app behavior :( 
You looks as an expert in Chromecast, and I hope, you can provide some useful advises for me.

**Comment by Tapanila** [comment]
Sorry for a slow response. I don't currently have much time to spend on this project and all of that is going to refactoring. After I land that one I will be able to support with other stuff. Sorry for the inconvenience

**Comment by sensboston** [comment]
[CastMessage.patch.txt](https://github.com/Tapanila/SharpCaster/files/1393370/CastMessage.patch.txt)
OK, I found a resolution at least for the one issue. It looks like Chromecast is a **damn slow** in downscaling images! According to the [docs](https://developers.google.com/cast/docs/media),
> Images have a display size limitation of 720p (1280x720). Images should be optimized to 1280x720 or less to avoid scaling down on the receiver device.

Hmm, 720p on 4K TV... Google, you should be kidding! By the way, I've added code to downscale and rotate images and now (at least for slideshow) huge delays are gone. 

Teemu, AFAIK, Google also have **Chromecast Ultra** in stock. Do you know, how to detect/determine Chromecast model and what is the optimal images resolution for Ultra?

P.S. I found strange glitch in the code on project running on W10M arm, on the phone. Sometime (but not all the time!) this code
```
dynamic stuff = JsonConvert.DeserializeObject(PayloadUtf8);
return stuff.type;
```
throws an exception. I created small patch for you, to get rid of JsonConvert and dynamic for parsing type in message.

**Comment by Tapanila** [comment]
Thanks for the small patch and good job on noticing the downscaling issues with chromecast.

The discovery part of current implementation doesn't expose the information of Chromecast device. I have code for it ready on Refactoring branch. But haven't looked at what value is chromecast ultra returning so will need to check it and then document it.

**Comment by hieuvn** [comment]
Hi @sensboston,
your sample about Slideshow is very intersting, but it's for fixed Folder @slideshow or we could set this folder dynamic? For exemple those images can be taken from Open picker and we re-write index.html accordingly? Please give some ideas, thanks.

**Comment by sensboston** [comment]
@hieuvn, I've added hardcoded folder with the images just for demo purposes (to work everywhere). Of course you can use file picker/custom view with image selections - whatever you want. You may check my app called "Cast to" in the Microsoft Store.

The only thing you need to provide is correct handling of HTTP GET request for your images.

**Comment by hieuvn** [comment]
@sensboston ,thanks for your hint.
my test code is for casting video mp4 to chromecast with sharpcaster, but it work for first video only, i think to your slideshows image , it's maybe apply to playing playlist of video or music.

**Comment by sensboston** [comment]
You need to provide a **new** video file via HTTP server before calling `await _controller.LoadMedia(GetLocalAddress() + newFileName + "?nocache=" + _rnd.Next(int.MaxValue).ToString(), mediaFile.ContentType, metadata);`

```
                        StorageFile mediaFile = mediaItem.File;

                        HttpFolderResource.FileList.Clear();
                        HttpFolderResource.FileList.Add(mediaFile);

                        if (_resource != null) _httpServer.Unregister(_resource);
                        _resource = new HttpFolderResource("", Path.GetDirectoryName(mediaFile.Path), false, false, true, true);
                        _httpServer.Register(_resource);

```

P.S. Sorry, I just did a copy&paste from my working code but probably you've got an idea.

**Comment by hieuvn** [comment]
thanks @sensboston , i don't use Waher HTTP server, but a custom HttpServer:
_httpServer=new HttpServer(LocalPort)
_httpServer.StartServer();

and after i pass storagefile parameter as below:
_httpServer.filemp4=mediafile;

i will try your code when i'm at home and let you know.

**Comment by hieuvn** [comment]
@sensboston, you are the best! i got it working now.
the magic line was:  newFileName + "?nocache=" + _rnd.Next(int.MaxValue).ToString()
thanks again.

**Comment by Deery5000** [comment]
Anyone care to share some code for local media play back in UWP?

I'm using an embedded web server but I cannot get the media to play

`  SimpleHTTPServer myServer = new SimpleHTTPServer(@"C:\Users\deery\Desktop\Movies\The Pagemaster (1994) [1080p]");
            HttpWebRequest request = (HttpWebRequest)System.Net.WebRequest.Create("http://localhost:" + myServer.Port.ToString() + "/The.Pagemaster.1994.1080p.BluRay.x264.YIFY.mp4");
            request.AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate;`

` using (HttpWebResponse response = (HttpWebResponse)request.GetResponse())
            {
                var track = new Track
                {
                    Name = "English Subtitle",
                    TrackId = 100,
                    Type = "TEXT",
                    SubType = "captions",
                    Language = "en-US",
                    TrackContentId = response.ResponseUri.ToString()

                };

                IMetadata data = new MovieMediaMetadata();
                data.title = "test";
                data.metadataType = Models.Enums.MetadataTypeEnum.MOVIE;
                
                await _controller.LoadMedia(response.ResponseUri.ToString() + "?nocache=" + rnd.Next(int.MaxValue).ToString(),
                    response.ContentType, data, "BUFFERED", 0D, null, new[] { track }, new[] { 100 });

            }`
