### ISSUE TITLE
Live-stream support

### ISSUE THREAD

**Issue by haraldjordan78** [Tapanila/SharpCaster#129]
Thanks for this great project, it makes life much easier.
I have a hard time to get out what livestream options i have besides the smooth streaming (it requires IIS but i need something more portable.
Tried loading hls by m3u8 into SharpCasterDemoController, changed appid to default player in SharpCasterDemoController but it did not load.
rtmp doesnt seem to be supported. 

Do i really need to register my own appid and develop a receiver for it?

**Comment by Tapanila** [comment]
Hey,

Here's all supported media formats:
https://developers.google.com/cast/docs/media

You should be able to do it with the demo player but not sure why it fails.
You should also test the source material works with android/ios/chromec Chromecast SDK

**Comment by haraldjordan78** [comment]
Thanks for the prompt response!
I guess i understand now what the issue might be with HLS, There is no native support for HLS in Chromecast. Chromecast can more or less be seen as the Video object in HTML5... Correct? 

Google describes how to use HLS here: https://developers.google.com/cast/docs/player
"Using the Media Player Library" - that looks like a javascript only sending app.  

I did not yet figure out how this all maps to SharpCaster. In the javasript "Media Player Library", they use the following lines:

var host = new cast.player.api.Host({'mediaElement':mediaElement, 'url':url});
protocol = cast.player.api.CreateHlsStreamingProtocol(host);
window.player.load(protocol, initStart);

I'll try to experiement and if i get any results i'll update here.

**Comment by Tapanila** [comment]
So chromecast is basically a chrome browser running on dedicated hardware.

SharpCaster is an SDK which you can use to send commands to that browser. You can't really extend any of the functionalities from SharpCaster you can only send/receive commands. 

Chrome (javascript) version:
https://developers.google.com/cast/docs/chrome_sender_integrate

Android version:
https://developers.google.com/cast/docs/android_sender_integrate

SharpCaster is just C# implementation. I built this originally to support Chromecast for Windows Phone but that project was canceled.

**Comment by haraldjordan78** [comment]
The good news are that HLS m3u8 streaming works just as you said at the very start out of the box. I was not able to open any HLS stream from the web, like those:
https://bitmovin.com/mpeg-dash-hls-examples-sample-streams/

but in my local test setup with an apache hosted by xampp and the following ffmpeg command, chrome just plays the hls stream fine. 
ffmpeg -re -i %sourcefile% -s 640x360 -hls_list_size 30 -hls_flags delete_segments+append_list+omit_endlist -hls_list_size 1 -hls_time 1 -f hls c:\xampp\htdocs\out.m3u8

It took a while to figure this out and the above m3u8 output does not play in any of my browsers, just in chromecast (tried video.js and hls.js).

Anyway thanks that you are still there for us Tapanila!

**Comment by Tapanila** [comment]
Great that you got it working
