### ISSUE TITLE
add Reconnection feature

### ISSUE THREAD

**Issue by hieuvn** [Tapanila/SharpCaster#132]
@Tapanila, please add reconnection feature as descripte in Document:
[https://developers.google.com/cast/v2/reconnection](https://developers.google.com/cast/v2/reconnection)
Thanks

**Comment by marufbd** [comment]
due to this, i guess i am facing a lot timeoutexception and ioexception very frequently.

**Comment by Tapanila** [comment]
I'm currently very limited with the time that I can spend on this project so won't be able to commit to fixing this. Sorry about that

**Comment by Animeshdfoe** [comment]
I am also facing the same issues
