### ISSUE TITLE
Local Image and video Casting 

### ISSUE THREAD

**Issue by Animeshdfoe** [Tapanila/SharpCaster#136]
Hi,
    I am trying to create chromecast for casting local media from Universal windows App.But i am not getting that things. How to able cast local Media from Universal windows App. Give Me some idea.

Thanks

**Comment by Tapanila** [comment]
If you want to cast local media you need to create a web server on your UWP app and then you can cast those media. Then the flow would be following:

- Host media on UWP app. So you can get an address like this: http://10.30.28.12/media.jpg then you can send that to Chromecast
- Chromecast needs to be able to reach the server and get the picture data as a response when trying to reach the URL

Overall I don't recommend using local media with chromecast.
