### ISSUE TITLE
Can this SDK be used with Google Home Mini?

### ISSUE THREAD

**Issue by TriStarGod** [Tapanila/SharpCaster#138]
Can this SDK be used with Google Home Mini?

**Comment by nomadyow** [comment]
Tagging along - I'd also like to know this.  As it stands, SharpCaster finds my chromecast unit but not my Google Home/GH mini devices.

**Comment by kakone** [comment]
Currently, the device detection uses SSDP (cf #106), that must be the problem.

**Comment by nomadyow** [comment]
I just tried tmds.MDns using the serviceType _googlecast._tcp and it found my chromecast ultra and 4 google homes on the local network.  - That does seem to be a reliable method (for me).

**Comment by kakone** [comment]
Yes, with mDNS, it works. I use it in my [own library](https://github.com/kakone/GoogleCast), I didn't have any detection problem.

**Comment by lukizel** [comment]
Will work. Google Homes essentially also work as Chromecast Audio devices.
