### ISSUE TITLE
Xamarin Forms PCL or .NetStandard

### ISSUE THREAD

**Issue by andersonvieiragomeslopes** [Tapanila/SharpCaster#139]
Does it work with Xamarin Forms? If yes, how to implement?

**Comment by andersonvieiragomeslopes** [comment]
Update:
I tried to run the project, in the code do not appear errors, but the android application does not even work.

**Comment by Tapanila** [comment]
Planned to .net core port which you can find on branch but haven't really worked on this project for a long while. Might finish it one day but probably not
