### ISSUE TITLE
_chromecastService.StartLocatingDevices() returns 0 devices

### ISSUE THREAD

**Issue by cjkarande** [Tapanila/SharpCaster#140]
Hi
Am trying to locate my Panasonic Viera Smart TV which is connected to my Wifi, however the _chromecastService.StartLocatingDevices() API always returns 0 devices. I have even tried with my phone IP address, still the same result.

Am using it in my Xamarin Forms App. 
Xamarin Forms Version 3.0.0.561731
Android SDK version Minimum (4.4) and Target (8.1).

Pls let me know if you need any more details

**Comment by Tapanila** [comment]
The code is filtering the results to only return chromecast devices. You would need to change the filtering logic to get back your Viera Smart TV

**Comment by cjkarande** [comment]
Sorry i couldn't get that. Can you please elaborate it a bit more?
Following is the snippet of the code that am using.  192.168.1.12 is my
Phone's IP Address. Are you indicating that i should be using some other
API? if so then which one?

Appreciate you support.

private async void LoadChromecasts()
        {
            var foundChromecasts = await
_chromecastService.StartLocatingDevices("192.168.1.12");
            foreach (var foundChromecast in foundChromecasts)
            {
                Chromecasts.Add(foundChromecast);
            }
        }

**Comment by andersonvieiragomeslopes** [comment]
@cjkarande How did you get the xamarin.forms to work with the chromecast? Could you share the code?

**Comment by Tapanila** [comment]
You would need to change this line  
`var deviceType = "urn:dial-multiscreen-org:device:dial:1"; `
on DeviceLocator.cs file
