### ISSUE TITLE
Launching Netflix Via SDK - REQUEST

### ISSUE THREAD

**Issue by andreweberle** [Tapanila/SharpCaster#142]
Just looking at this library, very nice indeed, however, is it possible to launch Netflix with this sdk? If not what would you suggest? I had a look for a Netflix sdk, but even if i found that, integrating it with this library might be a whole other issue.

**Comment by Tapanila** [comment]
You could launch the Netflix App with this but then you would need to use the Netflix API to connect the Chromecast Netflix Application session with Netflix session (Not publicly documented APIs) Same issue as with YouTube.

I'm not planning to work on this as it would be pretty large task
