### ISSUE TITLE
Cast from local NAS

### ISSUE THREAD

**Issue by tomCasterPedersen** [Tapanila/SharpCaster#143]
Hello!

I am trying to cast a picture residing on my local NAS, but it does not work.

I have tried to enable NFS on the NAS and hoped that I could simply refer to the file in LoadMedia in the following format:

\\servernameOrIpAddress\Root\Picture.jpg

Would this approach actually work? I have not been able to open/invoke the picture from my Windows file explorer nor interface browser either, so I guess I haven't successfully setup NFS,  but curious if it would work...

If not; what should I do to cast local media files?

Thanks in advance..
Best rgds,
Tom

**Comment by Tapanila** [comment]
You can only cast from NAS if it allows streaming with HTTP(S) protocol. So if you can host an webserver on your NAS it should work fine
