### ISSUE TITLE
Trouble connecting to chromecast from desktop

### ISSUE THREAD

**Issue by foote-Greg** [Tapanila/SharpCaster#145]
Awesome Library !! 

When I use the following code

await ChromecastService.Current.StartLocatingDevices("192.168.0.61");

It will find  2 chromecasts but it will only connect to one of them. I am running this code from a UWP app on a windows 10 desktop computer that is connected via ethernet to the router which has a wired ports and is also a 2.4G and 5G Wireless.

Chrome on this desktop has no problem finding both chromecasts and connecting to and casting to both...

Is there something special I can do to connect in this situation where there may be multiple networks ? Extenders also create additional networks as well...

Thanks !!

**Comment by Tapanila** [comment]
So you have multiple network interfaces on your desktop? Basically, by specifying your IP Address it should work fine. Are you trying to connect both of them at once?

**Comment by foote-Greg** [comment]
No I think the router/wireless modem (Netgear C6300) is creating different networks  one for the 5G capable devices, one for 2.5 g, and one for the wifi extender

![image](https://user-images.githubusercontent.com/4241394/55917541-45d05480-5bb5-11e9-92c4-f8eec755b811.png)

**Comment by foote-Greg** [comment]
So the call to StartLocatingDevices will find the devices that are on the 2.5g network or the extended wifi network but I cannot get this code to work when the chromecast is on the other networks...

But Google Chrome can connect and cast to them fine from this desktop machine...

This fails when the chromecast is on the other networks:
await ChromecastService.Current.ConnectToChromecast(chromecast);

**Comment by foote-Greg** [comment]
How should I go about trying to debug this ?

**Comment by Tapanila** [comment]
Sounds strange. I would need to be able to reproduce this but if this is related to Netgear device then I don't see this happening.

You could try to debug this with Wireshark but that will be hard.
