### ISSUE TITLE
How to cast an Local Image?

### ISSUE THREAD

**Issue by vishal-parmar** [Tapanila/SharpCaster#146]
I have a Chromecast to test with. I can successfully find and connect to the Chromecast, but I can't figure out how to simply Display Local Image  If there Possible?

**Comment by Tapanila** [comment]
Chromecast can't display local image. The only way to cast "local image" is to have a webserver running on your local machine, which is responding to chromecast when it asks the image and even then you need to use an URL for it.

**Comment by vishal-parmar** [comment]
I am heartily thankful you sir. your Given solution is working.
