### ISSUE TITLE
Restarting previous app?

### ISSUE THREAD

**Issue by alexbk66** [Tapanila/SharpCaster#147]
I'm using SharpCaster in the app I'm creating - I direct TTS messages to Google Home.

Problem is - if there's some app already on Google Home (or Chromecast), i.e. Youtube or Spotify - the TTS announcement stops the current app.  Which is really bad.  And useless.

So I was wondering if there's any way I could remember the app ID and Content ID before TTS announcement and then restore the previous app after?

If it was possible, another usage would be collecting history and then been able to reply from the history - that would be really great!

**Comment by alexbk66** [comment]
It looks like it's possible to create a new app given the app I save, SharpCasterDemoController is a good example.  But then I need the mediaUrl to call LoadMedia() - which I don't have for Spotify, there's only contentID.  

So my guess is - it's not really possible to restart previous app/content?

**Comment by Tapanila** [comment]
So most of the applications on chromecast are easy. In the way that you can restart them by asking what's the current state and then you can return it.

There are few special applications the most known ones are Spotify, Netflix, and YouTube. All of these applications only start the chromecast application with chromecast SDK and after that, they connect the chromecast application to their backend and rest of communication is happening on the backend.

So this means you can't restore the state with SharpCaster but you would need to use their APIs to restore and they don't have any public APIs for this purpose. You can still start the application but that doesn't really help you at all.

**Comment by alexbk66** [comment]
There's a Spotify API, can you please at least give some directions, so I could add Spotify controller?

https://johnnycrazy.github.io/SpotifyAPI-NET/web/getting_started.html
