### ISSUE TITLE
Application ideas/suggestions

### ISSUE THREAD

**Issue by tapanila** [tapanila/SharpCaster#15]
I'm currently looking for an idea/suggestion for an app that would be leveraging the SharpCaster library

**Comment by 556556bt** [comment]
it will be great if it can support m3u8 HLS stream with loading of external subtitle SRT and audio tracking switching.

**Comment by tapanila** [comment]
If you know some existing chromecast receiver application that has those functions I can add the capabilities to SharpCaster and build an Windows application that uses all of those features.

**Comment by wind-rider** [comment]
idea: integration in a home automation app (possibly running on Windows 10 IoT Core e.g. on a Raspberry 3) controlled by [Nuimo](https://github.com/getsenic/nuimo-windows); together with [Philips hue](https://github.com/Q42/Q42.HueApi)

**Comment by tapanila** [comment]
@wind-rider Nuimo looks really interesting device and their library looked pretty straight forward.

But without the device I will probably not do anything related to it.

**Comment by juliotec** [comment]
Can you add subtitles?

**Comment by haraldjordan78** [comment]
m3u8 HLS support would really be great as @556556bt writes. I guess it should work using the default receiver app but i tried changing the app id of sharpcaster to the default player, specified the url of my m3u8 and used application/x-mpegurl or application/vnd.apple.mpegurl insetad of mp4 but it did not work... URL: https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8
