### ISSUE TITLE
Get current video information started by other app

### ISSUE THREAD

**Issue by MozzieMD** [tapanila/SharpCaster#16]
How to get current video on chromecast, title and poster of the video, cast is started by other app!?

**Comment by tapanila** [comment]
I was missing the metadata retrieval.
Just added it and releases a new nuget package.
I don't have any application that is using this so not 100% sure that it works.

1. Register for MediaStatus changed
2. call GetMediaStatus
3. MediaStatus.media.metadata got the fields

**Comment by MozzieMD** [comment]
```
            DeviceLocator deviceLocator = new DeviceLocator();
            var cancellationTokenSource = new CancellationTokenSource();
            cancellationTokenSource.CancelAfter(5000);
            List<Chromecast> chromecasts = await deviceLocator.LocateDevicesAsync(cancellationTokenSource.Token);
            var chromecast = chromecasts.First();
            var client = new ChromeCastClient();
            
            client.MediaStatusChanged += async (s, a) =>
            {
                await client.GetMediaStatus();
                Debug.WriteLine(client.MediaStatus.media.metadata.title);
            };
            client.ConnectChromecast(chromecast.DeviceUri);
```
I have this code, getting "Microsoft.CSharp.RuntimeBinder.RuntimeBinderException" в Microsoft.CSharp.dll, what can be the problem?

**Comment by tapanila** [comment]
DeviceLocator deviceLocator = new DeviceLocator();
            var cancellationTokenSource = new CancellationTokenSource();
            cancellationTokenSource.CancelAfter(5000);
            List<Chromecast> chromecasts = await deviceLocator.LocateDevicesAsync(cancellationTokenSource.Token);
            var chromecast = chromecasts.First();
            var client = new ChromeCastClient();

           client.Connected += async (s, a) => {
               await client.LaunchApplication(ApplicationId);
               await client.GetMediaStatus();
           };

            client.MediaStatusChanged += async (s, a) =>
            {
                Debug.WriteLine(client.MediaStatus.media.metadata.title);
            };
            client.ConnectChromecast(chromecast.DeviceUri);


Here would be the way to do it

**Comment by MozzieMD** [comment]
Thanks, i will get home and try itv😏

**Comment by MozzieMD** [comment]
well, same exception, even when just loading media i get this exception but streaming is ok, what about metadata can't get it to work, and how can i set for my stream video title and image. Now it's showing sharpcaster demo reciever in place of the video title

**Comment by tapanila** [comment]
Do you know an application that uses the metadata? I will build a complete sample to verify it.

**Comment by MozzieMD** [comment]
Google Chromecast app on android, shows metadata

**Comment by tapanila** [comment]
There was some issues with metadata parsing before but seems to work fine now.
