### ISSUE TITLE
Connect-Launch-Load Example does not work when no App loaded or different AppId loaded.

### ISSUE THREAD

**Issue by RobertK66** [Tapanila/SharpCaster#161]
Hi,
I am not sure if your statement "I won't be adding any new features" also applies to bugs and issues.
I am very happy that you did a refactoring to NET 2.0 Standard. I am revisiting this code that I am using for a long time in my own audio cast application. 

Testing with the simple Example from your readme page I do have 3 reproducable cases with my Audio-Casting device:

A – App “B3419EF5” already loaded
B - no App loaded at all
C – another App Id loaded

In A everythink works fine and the media is loaded.

In B and C the Load Media gets a 'CLOSE' answer and hits a timeout. When restarting the code it works (but this is because now the App is loaded already and we have case A now)

I think the problem comes with the LaunchApplicationAsync(…) method. Only in case of successful ‘joinExistingApplicationSession’ the Channel.ConnectAsync() gets called with the transportId. For new or changed Application this is never done. 

I could write an workaround from outside of your code by either calling this connect or calling the Load a 2nd time (with join = true) now. 

```
    var client = new ChromecastClient();
    var st = await client.ConnectChromecast(cc);
    if (st.Applications?.Count > 0) {
        Console.WriteLine("***** App running");
        if (st.Applications.FirstOrDefault(x => x.AppId == myAppId) != null) {
            // Our App is running. Lets join it
            Console.WriteLine("***** Join It");
            _ = await client.LaunchApplicationAsync(myAppId, true);
        } else {
            // Another App is running call without join feature
            Console.WriteLine("***** Launch with other (our) AppId");
            var stat = await client.LaunchApplicationAsync(myAppId, false);
            // This does load the application but media channel is not working yet 
            // We have to connect now.
            await client.GetChannel<IConnectionChannel>().ConnectAsync(stat.Applications[0].TransportId);
            //_ = await client.LaunchApplicationAsync(myAppId, true);
        }
    } else {
        Console.WriteLine("***** NO App running");
        // No App running  call without join feature
        Console.WriteLine("***** Launch with our AppId");
        var stat = await client.LaunchApplicationAsync(myAppId, false);
        // This does load the application but media channel is not working.
        // We have to connect now.
        await client.GetChannel<IConnectionChannel>().ConnectAsync(stat.Applications[0].TransportId);
        //_ = await client.LaunchApplicationAsync(myAppId, true);
    }
```

But I think the current behaviour of this method is not the expected and desired one.

**Comment by RobertK66** [comment]
I proposed a fix here: https://github.com/RobertK66/SharpCaster/tree/fix/Issue161

Side Note - as I used your UnitTests with my device (JBL Playlist - Audio Speaker):
My device does not change the TransportId if we re-join the Session. So I had to comment out the ConnectToChromecastAndLaunchApplicationTwice() Test

**Comment by Tapanila** [comment]
Fixed the issue, added new test cases and improved old ones
