### ISSUE TITLE
Not able to reference SharpCaster after installing Nuget Package

### ISSUE THREAD

**Issue by nightfrost** [tapanila/SharpCaster#18]
Hello,

I have a problem using this application, and I am almost sure that I'm missing something really trivial.
I use the nuget command to add SharpCaster, all is great, it installs and adds SharpCaster and Newtonsoft Json, all good.

Now I want to reference it at the top of my application, like: Using Sharpcaster.... But I am not able to find it... It would be a huge relief if you could help.

**Comment by nightfrost** [comment]
I had to manually add the .dll as reference... *facepalm*

**Comment by tapanila** [comment]
Hey,

What project type were you trying this with?
If you had to manually add the reference then I have made a mistake when creating the nuget package and will fix it so it is easier to use for others

**Comment by nightfrost** [comment]
I was running the Nuget installing (The Nuget Shell through Visual Studio), which added the Json itself, but I had to manually add the .dll to references.
I'm not entirely sure what you mean by Project type?

**Comment by tapanila** [comment]
SharpCaster only supports Windows & Windows Phone project types.
So even if you can manually add reference to the .dll which you should not be able to do for console application it would not work.

**Comment by nightfrost** [comment]
Fair dues, Thanks for the fast reply :)
