### ISSUE TITLE
Create a Fake/Virtual ChromeCast device

### ISSUE THREAD

**Issue by thomas-illiet** [Tapanila/SharpCaster#189]
Hello guys,

Can the SDK help create a Fake/Virtual ChromeCast device ?
Because i need this feature to create a ChromeCast device proxy for my personal usage.

kind regards
Thomas

**Comment by Tapanila** [comment]
This is a client SDK so it's not going to support your needs out of the box.
You could build a server SDK based on this but it would be a lot of work
