### ISSUE TITLE
Custom App Channel possible?

### ISSUE THREAD

**Issue by lucaschimweg** [tapanila/SharpCaster#19]
Hey!
I'm trying to extend the MediaPlayer in a Windows 10 UWP App with SharpCaster to a Chromecast.

I have built a custom receiver app, that communicates via a channel with my app. On Android, this works perfectly but I can't find how to open app channels with SharpCaster, Creating a channel with the `ChromecastChannel(client, "NS")` does not work for me... My code:

```csharp
chromecastClient.ApplicationStarted += (sender, application) =>
{
     var ch = new ChromecastChannel("*myappchannel*");
     ch.MessageReceived += (o, args) =>
     {
          Debugger.Break(); //Never triggered
     };
     var msg = new CastMessage { PayloadUtf8 = "{\"type\": \"MOVIE\", \"url\": \"myurl\"}" };
     await ch.Write(msg);
};
```

**Comment by tapanila** [comment]
If you could provide me your appid and example message so I can reproduce it I can verify it quickly.

It should support them. But haven't spend much tile testing it

**Comment by lucaschimweg** [comment]
The Problem is, that there is no way to register the cannels into the channels list in the ChromecastClient. I fixed it now with integrating my channel and my custom packets into the ChromecastClient.

**Comment by tapanila** [comment]
I made Channels a public so you can add your own custom channels into it in the future. This change is still on Dev branch because there's a lot of other stuff coming together with it.

Will probably land it on master and nuget next week.

**Comment by wind-rider** [comment]
Possible examples are
- https://dsaudio-chromecast.synology.com/dsaudio.html
- https://dsvideo-chromecast.synology.com/dsvideo.html

As you can see in the javascript, they use custom messages to control playback and media status.

Also they need an "identify"-message before they will even respond..

What do you think about having a Controller base class that can control DefaultMediaReceiver, where that base controller can be subclassed to implement connectivity with such other Custom Receivers?

Maybe the correct Controller implementation could even be loaded based on the AppId?
