### ISSUE TITLE
Idea: make pre-release nuget packages from your dev branch

### ISSUE THREAD

**Issue by wind-rider** [tapanila/SharpCaster#20]
It would be nice to release your dev branch as pre-release nuget versions so that people can try new features quicker

**Comment by tapanila** [comment]
I will not implement this idea at this point of time.

I aim to not have stuff on dev for longer periods of time and try to keep my changes smaller.

The refactoring to support another platform was bigger than I expected. Also the main reason why it's not merged to master is that the nuget packaging needs to be updated

**Comment by wind-rider** [comment]
> I aim to not have stuff on dev for longer periods of time
Good goal :+1: 

Which platforms do you want to support?

I tried upgrading the SharpCaster target framework to dotnet-standard-1.x (as an experiment) but I got compilation trouble (like the Generic.xaml not being able to build, etc)

**Comment by tapanila** [comment]
I currently have .NET 4.5.x, Windows 8.1 and Windows Phone 8.1.
Will look into adding dotnet-standard but not sure what's the status of socket APIs there.

Mainly did the .net 4.5.x support to practice building library that targets multiple platforms.

**Comment by wind-rider** [comment]
Ok.

Is there anything specific for which you want to keep the win8.1 (phone) support?

**Comment by tapanila** [comment]
It's to support UWP development. Mainly targeting Win10 but you can get win8.1 (phone) for free.

**Comment by wind-rider** [comment]
Aah, I thought that for UWP you had to create an UWP library or target windows 10

**Comment by tapanila** [comment]
Done. When pushing stuff into dev and wanting to publish just add -pre tag into it and it will be released ot nuget with the tag.
