### ISSUE TITLE
Can sharpcaster be used in mirror an android screen to chromecast?

### ISSUE THREAD

**Issue by noelitc** [Tapanila/SharpCaster#209]

**Comment by Tapanila** [comment]
Sharpcaster can be used to make chrome cast load the stream. It won't help you how to record your stream or how to serve that stream to the chrome cast.

**Comment by noelitc** [comment]
Thanks for your reply. Is it possible to just send a bitmap to chromecast, I can only find mentions of providing a url.?

**Comment by Tapanila** [comment]
Nope. You would need to send a URL to chromecast.

URL could point to a webserver that you are hosting and then you could upload a bitmap to that webserver which then shows it at that url

**Comment by noelitc** [comment]
I hope you don't mind the questions. As you know you can cast you android screen to a chromecast device using google home on android. Any ideas how that can work , I presume there are not uploading it to a server.  Maybe they are creating a streaming server on the android device.

**Comment by Tapanila** [comment]
Not at all.

That's a very good point and I had completely ignored that one.

Either there's something special on Chromecast protocol that allows that, but I haven't implemented which might be the case or they are using the android device as a server.

You could probably do a package capture on a network to see if the Chromecast starts to steam video from Android device. Not sure any other way to confirm that. I'm iOS and Windows user so don't currently have any android devices to test this.
