### ISSUE TITLE
Xamarin Ios

### ISSUE THREAD

**Issue by profilen** [Tapanila/SharpCaster#220]
Hi, Im trying to use the lib in my Xamarin Forms solution and everything works except that it take very long time to discover chrome cast devices on IOS. Everything works great on Android. Im using the FindReceiversAsync() repeatedly and it takes up to a minute or two to discover all available devices.

**Comment by Tapanila** [comment]
Have you tried to manually specify the timeout?

`            IChromecastLocator locator = new MdnsChromecastLocator();
            var cts = new CancellationTokenSource();
            cts.CancelAfter(TimeSpan.FromSeconds(30));
            var chromecasts = await locator.FindReceiversAsync(cts.Token);
            return chromecasts.First(x => x.Name == name);`
