### ISSUE TITLE
Remove console.Writeline() from ChromeCastClient.cs 

### ISSUE THREAD

**Issue by RobertK66** [Tapanila/SharpCaster#221]
Ok, finally ( - I think - ) I got the branches/merges right in my #218 Pull request. As I want to use your package from a console app, I could not control the output written by ChromCastClient(). 
My Pull request uses current version of Microsoft.Extensions.Logging. Default logging stays to Console only, but you can control it now by providing your own configured ILoggingFactory in the serviceCollection of the constructor.

Additional the pull request makes the 2 Messages I needed to overwrite public iso protected. (see #158 )

**Comment by Tapanila** [comment]
Thanks for the pull request. I just merged it and will push a new version of the package.

**Comment by Tapanila** [comment]
I changed a bit the implementation.
Default version of SharpCaster doesn't need to do console logging and not sure why I had it there in a first place.

I hope it's still fine for your implementation

**Comment by RobertK66** [comment]
Great, Yes I checked with your latest version in main. Everything is ok with that. Thx a lot! 😄

**Comment by RobertK66** [comment]
Ok moved my dependency to use the version 1.0.8 and everything works fine. 👍
