### ISSUE TITLE
Cant find sample application

### ISSUE THREAD

**Issue by nithinbandaru1** [Tapanila/SharpCaster#225]
Hi I am not able to find the sample application SharpCaster.Sample. I only found empty repo

https://github.com/Tapanila/SharpCaster.Samples

**Comment by Tapanila** [comment]
Hey,

The sample was on this repository but when I was doing refactoring or something I have deleted it.
Will add the WPF sample back to this repository but it will take few weeks before I will get into this

**Comment by Rainson12** [comment]
is there any update on this? I am struggeling to stream website content
