### ISSUE TITLE
_socket throws NullReferenceException

### ISSUE THREAD

**Issue by wind-rider** [tapanila/SharpCaster#25]
For some reason I get a nullReferenceException when running the Simple app and sending a message (by changing the volume or clicking play/pause).

Reproduction:
- run a song in DS Audio on Chromecast
- run the SharpCaster.Simple app
- click in the volume slider or click play/pause

Symptoms:
- Volume slider is zero
- Volume updates are not received
- NullReferenceException: _socket is null in ChromecastSocketService.cs (in SharpCaster.UniversalWindows) - this is on line 54 in Write(byte[] bytes)

**Comment by tapanila** [comment]
The sample app doesn't really handle all the stuff correctly.
You should wait till it connects to chromecast and starts application before trying to change volume
