### ISSUE TITLE
Idea: support for popular chromecast apps

### ISSUE THREAD

**Issue by wind-rider** [Tapanila/SharpCaster#26]
The current library targets Google's Default Media Receiver (message format and available operations).

However it would be nice if additional apps with their own protocol could be supported.

My idea would be something like this:
- Allow the ChromeCastClient client to use different controller implementations
- Register controller implementations along with their respective AppId
- Let ChromeCastClient automatically load the right controller for the current app

@tapanila what do you think?

Also have a look at https://github.com/balloob/pychromecast/pull/101 (here I implemented a controller for DS Audio)

**Comment by Tapanila** [comment]
I plan to make more controllers in the future. But will focus on specific applications if people ask for them.
