### ISSUE TITLE
Support disconnecting from a chromecast

### ISSUE THREAD

**Issue by Tapanila** [Tapanila/SharpCaster#28]

**Comment by tapanila** [comment]
This is really weird. If anybody has any thoughts how to implement this I would be really interested to talking you about this.

**Comment by wind-rider** [comment]
Maybe not the cleanest way, but what happens if you stop sending ping pong messsages on the heartbeat channel?

Or if you just close the socket connection?

**Comment by tapanila** [comment]
I want to make it so after disconnection you can connect to a new chromecast or same one. So basically disposing the underlying socket, stopping the heartbeat and then creating them again or something like that

**Comment by wind-rider** [comment]
Does the new connection need to be done from the same chromecastclient object? I think it is also possible just to create a new instance and optionally to implement idisposable in chromecastclient?

**Comment by tapanila** [comment]
Yep. But then the events are bit tricky. Since the event handlers are hooked into the client and if recreated you loose them.

But I think that might be the best way to go

**Comment by ovesennet** [comment]
Any  more progress on this? I try to use SharpCaster, but without any way to disconnect and reconnect, it's pretty useless for my scenario.

**Comment by Tapanila** [comment]
I got pretty far but started doing other stuff. I will take a look at this on the coming weekend, will post here the status on Sunday.

**Comment by Tapanila** [comment]
This is now supported on dev branch.

Might take a while for all of it to be pushed to master and nuget.
