### ISSUE TITLE
the TRACE log for received message goes to wrong logger.

### ISSUE THREAD

**Issue by RobertK66** [Tapanila/SharpCaster#302]
Hi using version 1.1.3 now, I found that we missed somehow this line (155 in ChromeCastClient) when merging/pulling/releasing...

_logger?.LogTrace($"RECEIVED: {payload}");

should be:

channel?._logger?.LogTrace($"RECEIVED: {payload}");

**Comment by Tapanila** [comment]
I made mistake when merging some changes. Will fix it

**Comment by Tapanila** [comment]
Fixed in 1.1.14
