### ISSUE TITLE
Crash when I connect to chromecast

### ISSUE THREAD

**Issue by dkler00** [tapanila/SharpCaster#31]
My uwp app crash when i try connect to chromecast. 
I select device and try to connect then ( Uri and friendlyName is correct).
Error message : (CoreCLR: CoreCLR_UWP_Domain) : Chargé 'Anonymously Hosted DynamicMethods Assembly'. 

thanks
PS, sorry for my english :(

**Comment by tapanila** [comment]
Can you try again with 0.1.6 nuget package?
