### ISSUE TITLE
Subtitle or Caption supporting?

### ISSUE THREAD

**Issue by juliotec** [tapanila/SharpCaster#33]
Hi, can sharpcaster supporting caption or subtitles? I cant find MediaTracks option just CustomData,

Im a C# .net develop and xamarin too, im looking to cast witth captions or subtitles, i see that you using json to send to chromecast messages, should be good send the subtitle url there too, i have been using Google Services Cast but i dont like it, I like your develop to using in xamarin, but i need captions too. thanks for your work, can you tell me where or a suggestion to add subtitles to the sharpcaster?

**Comment by tapanila** [comment]
Hey,

I can add Tracks object into MediaInfo to support the selection of caption track.

Currently my library doesn't support Xamarin. To support Xamarin you would need to change the targeting of SharpCaster.Portable, Create SharpCaster.Xamarin and implement the ISocketService and IChromecastSocketService

**Comment by tapanila** [comment]
I added support for captions on Captions branch.  https://github.com/tapanila/SharpCaster/commit/c4171d06a412babdb3f41134d7c96d75c5fb5900

Currently in progress of refactoring so it might take a while before I land it into a nuget package.

**Comment by juliotec** [comment]
Yes i added the portable project to support xamarin android, so thanks
