### ISSUE TITLE
Subtitles not working with some urls

### ISSUE THREAD

**Issue by juliotec** [tapanila/SharpCaster#36]
http://www.auctor.tv/Archivos/0/Media1/0/1.vtt this url dont work with the captions or subtitles, if you put it in the subtitles, dont work, i think that its a chromecast problem, im not sure what is happening, im not sure if is by using "https" protocol, because a http protocol to put subtitiles dont work.

**Comment by juliotec** [comment]
ok fiexed the problem was the CORS 

Access-Control-Allow-Origin: * must be in video and subtitles headers to can be played. in the HEADERS http request

**Comment by tapanila** [comment]
Good that you got it working
