### ISSUE TITLE
Use one solution for Continuous Integration and samples

### ISSUE THREAD

**Issue by wind-rider** [Tapanila/SharpCaster#37]
Now there are two solutions (one general one and one for CI).

It would be better to have only one only one .sln file.

I think this can be done in the following way:
- Use the solution configuration manager to create a specific "solution configuration" for CI
- Within that solution configration, uncheck "build" for all sample projects
- Configure AppVeyor to use the CI solution configuration instead of "Debug" or "Release". See https://www.appveyor.com/docs/build-configuration#build-matrix

I have no AppVeyor account so I couldn't test it, but I think that should work.

**Comment by Tapanila** [comment]
Closing this issue since we have not made any progress and it does not bother me
