### ISSUE TITLE
Xamarin support

### ISSUE THREAD

**Issue by tapanila** [tapanila/SharpCaster#38]

**Comment by juliotec** [comment]
So i cant make a xamarin support, Can you upload the protobuff sharpcaster code? the PCL is not compatible, http://danrigby.com/2014/04/16/xamarin-pcl-profile-notes/ checking i need the profile Profile 344 (.NET 4.5, Windows 8.0, Windows Phone Silverlight 8.0, Silverlight 5, Windows Phone 8.1) right now protobuff support is only Profile 151 (.NET 4.5.1, Windows 8.1, Windows Phone 8.1) (netstandard 1.2), no xamarin, or is there a way to used to xamarin?

**Comment by juliotec** [comment]
https://github.com/rdavisau/sockets-for-pcl this project use sockets for pcl, i think that can be ChromecastSocketService and other services implemented in  services, im cheking

**Comment by tapanila** [comment]
Probobuff-sharpcaster can be found here https://github.com/tapanila/protobuf-net
If you get it to work with Profile 344 I would be very happy to accept a pull request and update the nuget package.

The Sockets for PCL looks really nice project. Converting the socket code from SharpCaster might be bit problematic but should be okay.

I'm personally looking into refactoring the logic and once I have done that. I will move into Xamarin support.

**Comment by tapanila** [comment]
There is now Xamarin support on Xamarin branch. https://github.com/tapanila/SharpCaster/tree/Xamarin

Haven't tested yet with Xamarin app but will do that later this week

**Comment by tapanila** [comment]
The Xamarin Branch does not really work.

I have played around with Android and it seems to require quite a lot of more work.

**Comment by tapanila** [comment]
Pre support for Xamarin has now landed
