### ISSUE TITLE
Plex & Chromecast?

### ISSUE THREAD

**Issue by Lakritzator** [tapanila/SharpCaster#51]
This is more of a question!

I was looking at #50 and just out of curiosity, not directly pointed at @wind-rider, what do Plex command have to do with Chomecast?

Wouldn't this pollute the project? I myself am a fan of having projects do one thing, and do it good... Having al kinds of features usually makes it hard to maintain, and e.g. a plex change would make other people upgrade the library without the need. Would the Plex stuff work when it was removed from the project into a different one?

Nothing against the functionality... keep up the good work!

**Comment by tapanila** [comment]
The plex stuff could be extracted out of the SDK and it would still work fine.

But I want to have 3-5 different application inside of the SDK. That way you can see how custom commands can be implemented by SDK. Most of the applications almost never update their Chromecast commands so I would not see that as a big risk. 

When we go further with the project I might create a structure where you extend the SDK with nuget packages. So you could have SharpCaster.Plex to support plex. But currently I would see that as too much work to justify the gains

**Comment by Lakritzator** [comment]
Thanks for the quick answer!

P.S.
To make refactoring possible in the future, maybe it's at least an idea to make it in separate namespaces?

**Comment by tapanila** [comment]
It is pretty easy to change namespaces with ReSharper so for now I will just keep them like they are.
