### ISSUE TITLE
Portable Sockets

### ISSUE THREAD

**Issue by woellij** [tapanila/SharpCaster#52]
Hi,

I stumbled upon your great project while researching options on supporting chromecast in windows apps.

A suggestion for future work would be to use already existing portable abstractions of UDP and TCP sockets (e.g. https://github.com/rdavisau/sockets-for-pcl which i've bee successfully working with)

I'm looking forward to future features.

Greetings

**Comment by tapanila** [comment]
I looked into that project. But they do not support the required options of the sockets that chromecast needs. (There is some really strange stuff, like non valid SSL certificate )

I will first complete the Xamarin port of the project and after that I will take a look if I could add all the needed features into that project.

**Comment by tapanila** [comment]
Thanks a lot for suggestion. I started to use that library for the implementation.
