### ISSUE TITLE
Difficult ReceiverChannel logic

### ISSUE THREAD

**Issue by wind-rider** [Tapanila/SharpCaster#54]
I'm having difficulty following the logic in ReceiverChannel.
- Why is await `ConnectToApplication(Client.ChromecastApplicationId);` called upon every ChromecastStatusResponse?
- Is it possible to have one ChromecastClient.ChromecastApplication(Id) that is updated upon receiving a ChromecastStatusResponse instead of manually setting it after launching an app? That way the currrent application id would always be filled with an up-to-date value.
- The need for two similar variables (Client.ChromecastApplicationId vs ChromecastClient.RunningApplication.AppId) confuses me

**Comment by Tapanila** [comment]
The logic is pretty confusing. But not planning to do any changes on it for now.

If you have an idea how to make it more simpler I will take any pull requests into review
