### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Tapanila** [Tapanila/SharpCaster#61]
- [x] Document creating new Controller
- [x] Document creating new Channel
- [x] Document all existing Controllers and Channels
- [x] Document all LoadMedia parameters (example metadata, duration, streamtype and etc)

**Comment by wind-rider** [comment]
What do you mean with documentation? Do you mean using XmlComments in Visual Studio? or setting up a Wiki?

**Comment by tapanila** [comment]
Writing more stuff to wiki and linking from readme into wiki

**Comment by Tapanila** [comment]
Wiki now has all the content
