### ISSUE TITLE
custom controller

### ISSUE THREAD

**Issue by furesoft** [Tapanila/SharpCaster#62]
hi, how can i implement a custom controller to stream a wpf application window?

**Comment by tapanila** [comment]
The SDK doesn't support streaming  your screen/window into chromecast.

I haven't looked if it would be possible. I might do that at some point but no promises

**Comment by wind-rider** [comment]
A possible option is to do this:

1. Create a http server in your own code
2. Write code that captures your window and encodes it to x264 video
3. Make an endpoint in the server that serves the x264 video
4. Send the url of the endpoint to a chromecast app using the LoadMedia command

Maybe you can take inspiration from here: https://github.com/Pat-Carter/stream2chromecast

**Comment by Tapanila** [comment]
Not planning to do any work with this for now
