### ISSUE TITLE
Move to .net Standard 2.0

### ISSUE THREAD

**Issue by Tapanila** [Tapanila/SharpCaster#69]
https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/

The library and all dependencies seem to be .net 2.0 compatible according to ApiPort.
So once 2.0 is out I will switch to target that one

**Comment by Tapanila** [comment]
Seems like this is not happening in a while. So closing this

**Comment by wind-rider** [comment]
This is scheduled for Spring 2017: https://github.com/dotnet/core/blob/master/roadmap.md

**Comment by Tapanila** [comment]
Yep. I would say 6 months is pretty long time and it might get delayed.
Also not planning to be in the first wave.
