### ISSUE TITLE
MusicTrackMediaMetadata does not display (album)artist

### ISSUE THREAD

**Issue by wesleyvano** [tapanila/SharpCaster#70]
MusicTrackMediaMetadata does not display (album)artist

VB.NET:
`metadata = New MusicTrackMediaMetadata() With { .albumArtist = artist, .artist = artist, .songName = song,  .title = song }` 

Both "artist" and "song" have a value, the song is getting displayed on my screen correctly but the artist isn't.

**Comment by tapanila** [comment]
Sorry for not responding to this.

Have been busy with stuff and currently travelling so have missed this. I will make sure to check this when I'm back in the end of November

**Comment by tapanila** [comment]
I made changes on the MusicTrackMediaMetadata to fix the issue on dev branch.

If you want to quickly just fix it yourself you can add this code
`metadata = New MusicTrackMediaMetadata() With { .albumArtist = artist, .artist = artist, .songName = song, .title = song, .metadataType = 3}`
