### ISSUE TITLE
Singleton instance getter is not thread safe

### ISSUE THREAD

**Issue by wanton7** [tapanila/SharpCaster#71]
There maybe other but instance property like this is not thread safe. Because of this possible race condition you might create multiple instances if it's called from multiple threads.

`
public static ChromecastService Current => _instance ?? (_instance = new ChromecastService());
`

use this instead
```
private static Lazy<ChromecastService> _current = new Lazy<ChromecastService>(() => new ChromecastService());  
public static ChromecastService Current { get { return _current .Value; } }
```

**Comment by tapanila** [comment]
Thanks for pointing this out.

I haven't really spent any time to make sure the code is thread safe so this kind of finds are really important.

I'm currently travelling and will get this fixed when I'm back at the end of November. If somebody wants to submit a pull request for this I would be happy to accept.

**Comment by tapanila** [comment]
I have now added the change to dev branch.

Will do a nuget release during a weekend
