### ISSUE TITLE
How put Media Title in metadata object

### ISSUE THREAD

**Issue by juliotec** [tapanila/SharpCaster#73]
I have a question, how can I put the title movie in the metadata object, but i dont have the mediatype numbers

GENERIC
Generic template suitable for most media types. Used by chrome.cast.media.GenericMediaMetadata.
MOVIE
A full length movie. Used by chrome.cast.media.MovieMediaMetadata.
TV_SHOW
An episode of a TV series. Used by chrome.cast.media.TvShowMediaMetadata.
MUSIC_TRACK
A music track. Used by chrome.cast.media.MusicTrackMediaMetadata.
PHOTO
Photo. Used by chrome.cast.media.PhotoMediaMetadata.

the MovieMetadata object need a int, do you know the numbers in int?

**Comment by juliotec** [comment]
Ok now i know GENERIC is number 0 and MOVIE is number 1

**Comment by tapanila** [comment]
I improved the experience of using metadata by adding enum for it.

So no more mysterious int to assign :)
