### ISSUE TITLE
Does not work on Windows 10 Iot

### ISSUE THREAD

**Issue by daninden** [Tapanila/SharpCaster#74]
I installed the latest SharpCaster nuget package on a Windows 10 IOT background task project.
On ChromecastService.Current.StartLocatingDevices I get the following error:

Could not load file or assembly 'Rssdp.Portable, Version=2.0.0.1, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

The Rssdp.Portable.dll which is distributed in Rssdp-sharpcaster is version 1.0.0.12

**Comment by tapanila** [comment]
Will check this during a weekend.

Were you trying this with Raspberry Pi?

**Comment by daninden** [comment]
Yes, this is running on a Raspberry PI, it seems that it requires a newer version of the Rssdp.Portable library, which is not in the Sharpcaster dependancies (which is Rssdp-sharpcaster).

**Comment by tapanila** [comment]
I think I have wrong dependencies listed on the current nuget package that is published

**Comment by daninden** [comment]
It seems you updated the references (in the .csproj file).

<Reference Include="Rssdp.Native, Version=2.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\Rssdp.2.0.0.1\lib\portable-net45+win+wpa81+wp80\Rssdp.Native.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Rssdp.Portable, Version=2.0.0.1, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\Rssdp.2.0.0.1\lib\portable-net45+win+wpa81+wp80\Rssdp.Portable.dll</HintPath>
      <Private>True</Private>
    </Reference>

but did not change the Nuget dependancies.

**Comment by daninden** [comment]
Thanks for the time, I will check for an update!

**Comment by tapanila** [comment]
Released an updated nuget package.

**Comment by Tapanila** [comment]
Verfied this working with Windows 10 IoT on Raspperry Pi 3
