### ISSUE TITLE
Unable to write data to the transport connection: The socket has been shut down.

### ISSUE THREAD

**Issue by nielscup** [Tapanila/SharpCaster#76]
I receive this error when calling  

`_controller = await ChromecastService.ChromeCastClient.LaunchSharpCaster();`

How do I fix this?

**Comment by tapanila** [comment]
Hey,

Were you able to connect to chromecast fine before doing that?
And are you talking about a sample project or your own project?

**Comment by nielscup** [comment]
I am using the sample Android project. I just found the cause of the issue: sometimes there are no devices returned and then this call `ChromecastService.ConnectToChromecast(devices.First());` causes the error.

however I am now unable to restart my app and start a new cast: the Sharpcaster Demo Receiver remains open on my TV when I close the app and I cannot cast anything anymore. Is there any documentation on how to properly close the cast before leaving the app and then reopen a new cast?

**Comment by tapanila** [comment]
I clearly need to improve the Android sample.

There is automatic timeout on Chromecast which is around 2 minutes so even if the application is left open there is no problems. 

If there is application open on Chromecast you can just send a open application command to Chromecast and it will open the new one or if it is the same application ID it will join the session.

Currently the documentation is really lacking

**Comment by nielscup** [comment]
That helps, thanks a lot!

**Comment by nielscup** [comment]
Hi Tapanila,

Would you be able to provide some sample code on how to reconnect to an open application? I am still unable to do so. I would expect to do something with ChromeCastClient.RunningApplication, but it is always null when I restart the app.

**Comment by tapanila** [comment]
When you do LaunchApplication by default it will reconnect to an open application.

The ChromeCastClient.RunningApplication is only populated after LaunchApplication has been called.

**Comment by nielscup** [comment]
But I have to connect to a Chromecast device before I can call LaunchApplication, right? 

Anyways, streaming media works the first time I launch my app. But I am still getting a couple of errors  when I quit the application and then restart it. I first connect to a chromecast device, and then call LaunchApplication on the _controller when connected to a chromecast device:

1) An unhandled exception occured.
caused by:
`public async Task ConnectWithDestination()
        {
            await Write(MessageFactory.ConnectWithDestination(Client.CurrentApplicationTransportId));
        }`

2) Unable to write data to the transport connection: The socket has bee shut down.

When I call StopApplication and the LaunchApplication I get the following error:

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'The Stream is closed.'.

Joining an existing application never happens in LaunchApplication.

**Comment by tapanila** [comment]
> But I have to connect to a Chromecast device before I can call LaunchApplication, right?

Yep

> Anyways, streaming media works the first time I launch my app. But I am still getting a couple of errors when I quit the application and then restart it.

Sorry but I do not understand what you are doing different after restarting? or how it is behaving differently after restart.

If you can share the code + steps how to reproduce the problem. That would help a lot with solving the issue

**Comment by Tapanila** [comment]
If this is still an issue just re-open this
