### ISSUE TITLE
Not working on Windows 10

### ISSUE THREAD

**Issue by Deery5000** [Tapanila/SharpCaster#77]
Hi ,

I tried the code :
 ObservableCollection<Chromecast> chromecasts = await ChromecastService.Current.StartLocatingDevices();

But receive this error 
An exception of type 'System.IO.FileLoadException' occurred in mscorlib.ni.dll but was not handled in user code

Additional information: Could not load file or assembly 'System.Runtime.WindowsRuntime, Version=4.0.11.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

New project for windows 10 used with framework 4.5.2

Any ideas

**Comment by Tapanila** [comment]
Hey,

Not sure if this was your issue, but I had wrong dependencies listed on 0.3.2 package.
So now there is [0.3.3-pre](https://www.nuget.org/packages/SharpCaster/0.3.3-pre) which works.

Sorry for the trouble.

**Comment by Flavien-Pensato** [comment]
Hey @Tapanila ,

I got the same error with 0.3.4 and 0.3.3-pre.

**Comment by Tapanila** [comment]
Could you send me the project to teemu(at)tapanila.net or create a new project where this can be reproduced.

**Comment by Flavien-Pensato** [comment]
Hi Tapanila,

I followed some instruction and remove my packages folder (/Users/Username/AppData/Local/Packages).

Then rebuild. Problem solve.

**Comment by Tapanila** [comment]
Awesome
