### ISSUE TITLE
0 Device found

### ISSUE THREAD

**Issue by kalpesh2804** [Tapanila/SharpCaster#78]
I have 6 devices connected on same network but still i am getting 0 devices.

below line return  0 devices or break execution.

 var foundDevices = await deviceLocator.SearchAsync("urn:dial-multiscreen-org:device:dial:1", TimeSpan.FromMilliseconds(5000));

**Comment by Tapanila** [comment]
Do you have multiple network cards or some kind of virtualization software installed?

There is currently some problems of RSSDP choosing the correct network card when there is multiple present.

**Comment by kalpesh2804** [comment]
SharpCast Simple demo can find devices list but SharpCast Console application can not find devices list.

**Comment by Tapanila** [comment]
Sounds strange. Do you have some firewall application running on your system?

The LoadMedia only supports [Media](https://developers.google.com/cast/docs/media).

**Comment by kalpesh2804** [comment]
yes, there is firewall. do i need to add setting in firewall ? 

how can i load WebPage / Html ?

**Comment by Tapanila** [comment]
Not sure about firewall settings. It depends which firewall product you are using but you can try if it is the cause by disabling it while testing.

The SharpCaster SDK does not currently support loading webpage / HTML

**Comment by kalpesh2804** [comment]
SharpCaster support only on PORT # 8009 ? is it limtiation ? can i change port # ?

**Comment by Tapanila** [comment]
SSDP itself uses 8009. Haven't researched into changing the port, you might be able to change it but the code related to SSDP is at[ RSSDP project](https://github.com/Yortw/RSSDP).
