### ISSUE TITLE
Play Video loop

### ISSUE THREAD

**Issue by kalpesh2804** [Tapanila/SharpCaster#80]
Hello,

How can i play single video in loop (once finished start again same video).

Thanks

**Comment by Tapanila** [comment]
Do you want the chromecast to handle the looping? or the sender?

If you can do it with sender (SharpCaster SDK) can handle it.
Just write a eventhandler for mediastate and when it changes just check if not playing then restart the video.

On chromecast itself I think you can get that effect but need to write a custom receiver application.

**Comment by Tapanila** [comment]
Here is sample how to do it with SharpCaster C# SDK on Windows 10 UWP Application

`public sealed partial class MainPage : Page
    {
        private SharpCasterDemoController _controller;
        private ChromecastService _service;
        private DateTime _previousStart;
        public MainPage()
        {
            this.InitializeComponent();
            _service = new ChromecastService();
            Loaded += MainPage_Loaded;
        }

        private async void MainPage_Loaded(object sender, RoutedEventArgs e)
        {
            _service.ChromeCastClient.ConnectedChanged += ChromeCastClient_ConnectedChanged;
            _service.ChromeCastClient.MediaStatusChanged += ChromeCastClient_MediaStatusChanged;
            var devices = await _service.StartLocatingDevices();
            if (devices.Count < 1)
            {
                //We do not have any chromecast devices so maybe raise an error or something?
                return;
            }

            _service.ConnectToChromecast(devices.First());
            
        }

        private void ChromeCastClient_MediaStatusChanged(object sender, Models.MediaStatus.MediaStatus e)
        {
            if (e.IdleReason != IdleReason.FINISHED) return;
            if (DateTime.Now.Subtract(_previousStart).TotalMinutes > 2)
            {
                LaunchVideo();
            }
        }

        private async void ChromeCastClient_ConnectedChanged(object sender, EventArgs e)
        {
            if (_controller == null)
            {
                _controller = await _service.ChromeCastClient.LaunchSharpCaster();
            }
            LaunchVideo();
        }

        private async void LaunchVideo()
        {
            await _controller.LoadMedia(
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/mp4/DesigningForGoogleCast.mp4",
    "video/mp4");
        }
    }`
