### ISSUE TITLE
working sample 

### ISSUE THREAD

**Issue by Deery5000** [Tapanila/SharpCaster#81]
Ive downloaded the sample but none of them work, when you load media I get and object reference error. In addition to this I have noticed something quite odd . . 

If I run the sample , I find the chromecast device but when I run it again it is not found, but if I disconnect the chromecast and reconnect it to the tv I can find it again 

On code page there is some sample code however _controller is giving me errors because it has not been initialized.

Can you send me a basic sample on how to search for device and send local media ie filepath to the chromecast.

UWP C# App

Thank you 
Kevin
deery5000@yahoo.co.uk

**Comment by Tapanila** [comment]
I broke the Windows 10 UWP project with the latest modifications. I will create a new version soon.
Currently only the Console application works

Sorry for the trouble

**Comment by Tapanila** [comment]
Version 0.3.4 is working now as are all the samples.
