### ISSUE TITLE
Reboot Device using SharpCaster

### ISSUE THREAD

**Issue by kalpesh2804** [Tapanila/SharpCaster#90]
I want to reboot device using SharpCaster.

Is it possible ?

**Comment by Tapanila** [comment]
I haven't seen reboot available from the official Android SDK.

I think currently only "Google Home" application is able to the reboot/restart of the chromecast. Will have to look if I can reproduce the command after looking into it.

Also if you know anyway to restart/reboot using chrome browser that would be helpful.

**Comment by kalpesh2804** [comment]
I found some reference.  please review it.

http://fiquett.com/2013/07/chromecast-traffic-sniffing/

**Comment by wind-rider** [comment]
@kalpesh2804 that is the old dial protocol, it's not being used anymore.
If you can reverse engineer the google home app or find another example then it might be possible; otherwise there is no way to find out what command to send.

**Comment by Tapanila** [comment]
Did not find a way to do this so closing this
