### ISSUE TITLE
Once chromecasts found, there not found a 2nd time

### ISSUE THREAD

**Issue by Deery5000** [Tapanila/SharpCaster#91]
Hi,

When I find chromecasts for the first time everything is great, however when I restart the app I never find any. 

If I remove the chromecast from the tv for a while and reinsert it, I can find them again.

Am I missing something here or is this an issue ?

Kevin :(

**Comment by Tapanila** [comment]
Hey,

Do you mean if you do the search again it does not find it? or that if you close the application and start it again it does not find it?

There should not be any this kind of issues.

**Comment by Deery5000** [comment]
Hi,

I tested again today with my own app, the sample UWP app and 2 different Chromecasts.

On the first and 2nd run (debugging is VS) I could see the devices  (even picks up the Fire stick), however after 20 minutes (Didn't search during this time) I was unable to find the devices.

I reset my router and both Chromecasts obtained a new IP Address, I was able to search for them again.

Using the Google Home app I was able to see the devices ok, however it said "Linked devices" which made me wonder if the issue is something by design by google

Should I be storing the Chromecast details in a database after ive successfully located them then creating a new Chromecast object with the DeviceUri?

Thank you

**Comment by Deery5000** [comment]
Is there any update on this ?

**Comment by Tapanila** [comment]
Hey,

No there is no need to build a local cache/database with results.
This code:
`ObservableCollection<Chromecast> chromecasts = await ChromecastService.Current.StartLocatingDevices();`

Should always return all the chromecasts that are found on the network. If this code doesn't give you the chromecast back on the 2nd run then it is really weird. If that happens could you check if the chrome browser on your desktop still sees them when it happens?

**Comment by Tapanila** [comment]
Could not reproduce the problem
