### ISSUE TITLE
Play Local Media Sample 

### ISSUE THREAD

**Issue by Deery5000** [Tapanila/SharpCaster#92]
The documentation is somewhat non existent however I have managed to get media playing in my app with the sample provide.

How do I cast local media ?

MovieMediaMetadata metadata = new MovieMediaMetadata() { metadataType = SharpCaster.Models.Enums.MetadataType.MOVIE, title = mainMovie.Title, releaseDate = mainMovie.Release_date };
          
            await _controller.LoadMedia(mainMovie.MediaLocation, "video/mp4", metadata, "NONE", 0D, null, null, new[] { 100 });

a quick sample of playing local media would be great

**Comment by Tapanila** [comment]
Hey,

Local media playback is bit hard to implement because of the design of Chromecast and it's not supported by official Android or iPhone SDK either.
You can still archive it by hosting the local files from your device and then sending an url to chromecast that points to your device that then server the files.

**Comment by Deery5000** [comment]
Hi, 

Ive decided to go with the local hosting by embedding a light weight webserver in my app to server local media to the chromecast via url.

If im successful ill post a reply here with my implementation. Might be something you can added to allow out of the box functionality.

I see other apps are offering local playback to chromecast so i know its possible 

Thanks
Kevin

**Comment by Tapanila** [comment]
I can definitely link it and if it works on every device (xbox, rasperry pi, desktop, xamarin and mobile) then I can also include it.

**Comment by jindal1979** [comment]
Hi,

My webserver works fine for ios and android with chromecast API, but its not working for windows uwp app with sharpcaster. Chromecast device request is coming to my webserver but after writing response to output socket stream....load failed error comes in logs send by chromecast....

And if i play same URL with browser or any third party app like "CnX Player"(uwp app) who supports http streaming then local file playback works very fine over the network means my local webserver is responding fine........

But with sharpcaster chromecast load failed error comes. 
Can anyone help me on this ?
