### ISSUE TITLE
load stream

### ISSUE THREAD

**Issue by BPIC1** [Tapanila/SharpCaster#95]
Is it possible, and how to send video/audio from a device connected to the laptop?

**Comment by wind-rider** [comment]
I'm afread there's no readily available solution; I think you have two options that will both require development:
- create an endpoint on your own laptop that will serve the stream as a video file (https://github.com/xat/castnow uses this approach)
- find out how the screen mirroring protocol works (some hints at https://github.com/thibauts/node-castv2-client/issues/14) and use that

**Comment by Tapanila** [comment]
Yep. Also I'm not planning to add anything on this project to enable this kind of solution.
