### ISSUE TITLE
Cast Youtube video

### ISSUE THREAD

**Issue by BPIC1** [Tapanila/SharpCaster#96]
Is there an example on how to cast a Youtube video starting from its code (http://youtu.be/CODE).

**Comment by Tapanila** [comment]
Nope.

The logic goes like this:
1. Start a youtube session in your application
2. Start chromecast youtube session on chromecast with SharpCaster SDK and receive ScreenID
3. Somehow connect the ScreenID to youtube session that you started on application
4. The youtube application on chromecast will start playing the videos and you can keep adding the videos by calling the youtube api with your applicatioon.

The youtube API seemed complex and didn't find any documentation about it. So I haven't made an sample for that.

**Comment by wind-rider** [comment]
You might have success by following the code at https://github.com/balloob/pychromecast/blob/master/pychromecast/controllers/youtube.py.

Let us know if it works! (Can't check it now)

**Comment by Tapanila** [comment]
I started to work on this but it is going slowly. Might have something ready in a month or so

**Comment by wind-rider** [comment]
I just saw your work in the branch, do you want to do some more advanced usecase? Or did they change the protocol?

Because in pychromecast they simply start the app and then send a message in the youtube namespace with this payload:
```json
        {
            "type": "flingVideo",
            "data": {
                "currentTime": 0,
                "videoId": youtube_id
            }
        }
```

Don't know if that still works, though.

**Comment by Tapanila** [comment]
That stuff on py stopped working months ago. So just trying to make it work

**Comment by wind-rider** [comment]
@Tapanila some small feedback - using [Refit](https://github.com/paulcbetts/refit) (available on [Nuget](https://www.nuget.org/packages/refit)) you can get cleaner code when calling REST APIs (in this case the youtube API). It will save you some maintenance :)

**Comment by Tapanila** [comment]
That is a good idea. I will anyway separate the youtube stuff to own nuget package when I get it working.

**Comment by Tapanila** [comment]
The youtube api is not documented at all and needs quite a bit of work. Not planning to do this anymore

**Comment by SDiesel** [comment]
If I understand you correctly, it's very simple.
You must add a method to the Youtubecontroller:
 public async Task LoadMedia(string mediaUrl)
        {
            await Client.MediaChannel.LoadMedia(
                           mediaUrl: mediaUrl,
                           contentType: "video", 
                           streamType: SharpCaster.Models.ChromecastRequests.StreamType.BUFFERED,
                           duration: 0D, customData: null, tracks: null, activeTrackIds: null, 
                           autoPlay: true, currentTime: 0);
        }
usage: 
            await _youTubeController.LoadMedia(mediaUrl:"07UFjPwzhOY");

**Comment by Tapanila** [comment]
Youtube is different from all the other applications I have seen.

1. You connect to youtube application on chromecast and receive YouTubeScreenId
2. You connect your browser youtube session into this YouTubeScreenId
3. Now everything you do on browser/app will be sent to YouTube chromecast application without going through your device. Instead, it will be youtube servers sending it to Chromecast application directly.

The pairing process is not documented at all and is pretty complicated.

**Comment by SDiesel** [comment]
I'm sorry, but this program code is working very well.
I checked this code on Phillips tv with SmartTV.
This is exactly what you wrote in P. 3.
Additional info, such as title, description, etc. I'm getting from NuGet package YoutobeExtractor.
P.S. Thank you for the great SDK

**Comment by Tapanila** [comment]
Very interesting. I will absolutely take a look into it.

**Comment by kmudov** [comment]
@SDiesel just tried your code and it doesn't work for me now in 2019. All my research leads to the 3 points mentioned by @Tapanila and the conclusion that the pairing process is not documented at all and is pretty complicated. Do you have any progress on this issue?

**Comment by Tapanila** [comment]
@kmudov haven't had any progress with this and I don't see myself having time to looking into this further.
