### ISSUE TITLE
Discovery finds Philips Hue

### ISSUE THREAD

**Issue by wind-rider** [Tapanila/SharpCaster#97]
For some reason, the dev branch discovery logic returns 3x Philips hue (I only have one) next to one Chromecast item.
We might add some filtering there (I see you have "urn:dial-multiscreen-org:device:dial:1" but still it responds)?

**Comment by Tapanila** [comment]
Can you repeat the behavior? I have a philips hue 1st and 2nd generation hubs and they do not show up on my machine.

If this keeps happening we should then add some filtering into the project.

**Comment by wind-rider** [comment]
Yesterday it happened almost every time with a checkout from your dev branch, but I don't know whether there are any other conditions.

I have a hue v1 and was connected via wifi.

**Comment by wind-rider** [comment]
today it also happened

**Comment by Tapanila** [comment]
I'm fine with the addition of some filtering code. I think we should use the device name parameter

**Comment by wind-rider** [comment]
I filtered using this:
```csharp
var deviceType = "urn:dial-multiscreen-org:device:dial:1";
deviceLocator.NotificationFilter = deviceType;
                
var foundDevices = await deviceLocator.SearchAsync(deviceType);
```

because even though deviceType was set in `deviceLocator.SearchAsync(deviceType)`, somehow my hue bridge answers...

**Comment by Tapanila** [comment]
Yep. It seems like the bridge v2 does respond. Bridge v1 didn't so didn't notice this.
Added this also
