### ISSUE TITLE
.Net Standard support

### ISSUE THREAD

**Issue by hansmbakker** [Tapanila/SharpCaster#99]
Out of interest I checked what the requirements would be to move to .Net Standard.

In order to be able to use sockets, .Net Standard 1.3 or higher is needed. This means that WP8.1 cannot be supported, but I saw you already dropped support for that.

.Net Standard 1.4 is the maximum since otherwise you can't use it from UWP apps.

After moving to Google's protobuf packages, all Nuget packages support .net standard 1.3 or higher.

The main issues are the `ChromecastSocketService` (needs implementation with `TcpClient` again; don't know about `SslStream`) and the `StreamSocketExtension` (don't know whether it is used but it uses the `Windows` namespace). 

Besides that, the console project and the test project need to be retargeted to .net 4.6.1.

After this change you would not need the "Sockets for PCL" Nuget package anymore.

**Comment by Tapanila** [comment]
I also looked into this. Currently, the only problem is SslStream it's not available on any net standard versions.

It is listed on .net standard 2.0 so when first release of that is out I will change this library into that so I can get rid of the sockets library dependency.

**Comment by wind-rider** [comment]
Ok, thanks for checking it :) hopefully UWP also gets an update so that it can reference something higher than net standard 1.4...

**Comment by Tapanila** [comment]
So .net standard 2.0 was released and also UWP support for it is coming.

Will first look into merging the protobuf changes and then I will take a look at changing to .net standard 2.0

**Comment by Tapanila** [comment]
You can do this now with preview stuff. but I will rather wait for real release before doing it.

**Comment by wind-rider** [comment]
Does the SDK for Fall Creators Update support .Net Standard 2.0 for UWP already? I didn't know.

**Comment by Tapanila** [comment]
Nope. There is going to be a release of uwp later this year with netstandard 2.0 support

**Comment by kakone** [comment]
[SslStream](http://packagesearch.azurewebsites.net/?q=sslstream) is available in .Net Standard 1.3 (you must add the [System.Net.Security](https://www.nuget.org/packages/System.Net.Security) nuget package).

I used it in [my own implementation of the GoogleCast protocol](https://github.com/kakone/GoogleCast) (.NetStandard 1.4 async way library).

**Comment by Tapanila** [comment]
Awesome! Was totally unaware of that and good job on implementing the GoogleCast protocol.

Will take a look at your implementation. I would love to get rid of pcl socket dependency.

**Comment by Tapanila** [comment]
So got the console sample working and library updated to .net standard.

System.Net.Security packages are not supported on UWP yet.
https://github.com/dotnet/corefx/issues/19783
So this switch will have to wait till UWP support is available before I merge it

**Comment by wind-rider** [comment]
Great!

Do you know what he means with ["available from the master branch"](https://github.com/dotnet/corefx/issues/19783#issuecomment-310222457)? Because that issue is closed now..

**Comment by Tapanila** [comment]
I think "Available from the master branch" means that the code is there but not released on nuget yet.

WPF or any other .net/.net core should work. It's just UWP that doesn't work

**Comment by CIPop** [comment]
@wind-rider, @Tapanila is correct: we're currently working on UWP and it will be available in our 2.1 release. 
While I've tested private builds, unfortunately, building an UWP app/lib using SslStream is not yet possible from the CoreFX/master branch.

**Comment by wind-rider** [comment]
https://blogs.msdn.microsoft.com/dotnet/2017/08/25/uwp-net-standard-2-0-preview/

**Comment by Tapanila** [comment]
Work is now done on #119
